Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2020-06, with the labels that each got.

#89 support injecting PROVIDER_ID in system environment
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/alicloud, priority/blocker, reviewed/lgtm

#94 fix issue eip_association cannot be destroyed
  charts/internal/alicloud-infra/templates/main.tf
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/alicloud, priority/normal, reviewed/lgtm

#95 Vendor gardener/gardener@b50098267f2577d06674903fa20032f1fe44894b
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/backupentry/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/infrastructure/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/reconciler.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/validation/seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/ingress_gateway.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/types.go
  vendor/modules.txt
Labels: area/open-source, kind/bug, needs/ok-to-test, platform/alicloud, priority/normal

#91 [ci:component:github.com/gardener/terraformer:v1.0.0->v1.1.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#96 [ci:component:github.com/gardener/machine-controller-manager:v0.29.0->v0.30.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#77 enable specified eips on snat
  charts/internal/alicloud-infra/templates/main.tf
  charts/internal/alicloud-infra/values.yaml
  hack/api-reference/api.md
  pkg/apis/alicloud/types_infrastructure.go
  pkg/apis/alicloud/v1alpha1/types_infrastructure.go
  pkg/apis/alicloud/v1alpha1/zz_generated.conversion.go
  pkg/apis/alicloud/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/alicloud/validation/infrastructure.go
  pkg/apis/alicloud/validation/infrastructure_test.go
  pkg/apis/alicloud/zz_generated.deepcopy.go
  pkg/controller/infrastructure/terraform.go
  pkg/controller/infrastructure/terraform_test.go
Labels: needs/ok-to-test, reviewed/lgtm

#97 Support multiple Alicloud disks when creating machines
  Dockerfile
  charts/internal/machineclass/templates/machineclass.yaml
  charts/internal/machineclass/values.yaml
  docs/usage-as-end-user.md
  example/30-worker.yaml
  pkg/apis/alicloud/validation/shoot.go
  pkg/apis/alicloud/validation/shoot_test.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/alicloud, priority/normal, reviewed/lgtm

#101 :sparkle: Enable server side encryption of buckets
  pkg/alicloud/client/client.go
Labels: area/security, kind/enhancement, needs/ok-to-test, platform/alicloud, priority/normal, reviewed/lgtm

#102 Wait for terraformer before deleting infrastructure
  go.mod
  go.sum
  pkg/controller/infrastructure/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/config.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/state.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/types.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/waiter.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/mock/gardener/extensions/terraformer/mocks.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go
  vendor/modules.txt
Labels: area/quality, area/robustness, kind/bug, needs/ok-to-test, platform/alicloud, priority/normal, reviewed/lgtm

#104 [ci:component:github.com/gardener/terraformer:v1.1.0->v1.2.0]
  charts/images.yaml
Labels: needs/ok-to-test

#105 [ci:component:github.com/gardener/machine-controller-manager:v0.30.0->v0.31.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#109 Delete running terraformer Pods before deleting infrastructure
  pkg/controller/infrastructure/actuator.go
Labels: area/quality, area/robustness, kind/bug, needs/ok-to-test, needs/review, platform/alicloud, priority/normal

#108 add rolling update strategy to deployment
  charts/gardener-extension-provider-alicloud/templates/deployment.yaml
  charts/gardener-extension-provider-alicloud/values.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/technical-debt, needs/ok-to-test, platform/alicloud, priority/normal

#106 Adapt to terraform v0.12 language changes
  charts/internal/alicloud-infra/templates/main.tf
  charts/internal/alicloud-infra/templates/variables.tf
  charts/internal/alicloud-infra/values.yaml
  pkg/controller/infrastructure/terraform.go
  pkg/controller/infrastructure/terraform_test.go
  pkg/controller/infrastructure/types.go
Labels: kind/cleanup, needs/ok-to-test, platform/alicloud, priority/normal, reviewed/lgtm

#111 [ci:component:github.com/gardener/terraformer:v1.2.0->v1.3.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm
