Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2021-06, with the labels that each got.

#301 Expose logs from user exposed components in the new way
  charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/configmap-observability.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#304 Update kubernetes-csi/livenessprobe
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#305 update deprecated fields
  pkg/controller/infrastructure/templates/main.tpl.tf
Labels: area/open-source, kind/enhancement, kind/test, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#308 Add support for nodeless dev setup in dev-setup-admission-alicloud.sh
  example/40-validatingwebhookconfiguration.yaml
  hack/dev-setup-admission-alicloud.sh
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, platform/alicloud, size/s

#307 Enhance validation of cloud provider secrets
  pkg/apis/alicloud/validation/secrets.go
  pkg/apis/alicloud/validation/secrets_test.go
Labels: area/ops-productivity, area/usability, kind/enhancement, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/s

#309 Add validation of Kubernetes feature gates
  pkg/admission/validator/shoot.go
  pkg/apis/alicloud/validation/controlplane.go
  pkg/apis/alicloud/validation/controlplane_test.go
Labels: area/ops-productivity, area/usability, kind/enhancement, kind/test, merge/squash, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/m

#315 Not to check valid values for immutable fields when updating of a shoot
  pkg/admission/validator/shoot.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#317 not to swallow output of make.sh
  hack/.ci/prepare_release
Labels: area/delivery, kind/cleanup, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#318 [test cicd release pipeline] Use full path in prepare release
  .ci/prepare_release
Labels: needs/review, reviewed/ok-to-test, size/xs

#319 [pipeline development] improve prepare_release
  vendor/github.com/gardener/gardener/hack/.ci/prepare_release
  vendor/github.com/gardener/gardener/hack/get-build-ld-flags.sh
Labels: needs/ok-to-test, needs/review, size/xs

#316 Update golang to 1.16.5 and alpine to 3.13.5
  .test-defs/infrastructure-test.yaml
  .test-defs/provider-alicloud.yaml
  Dockerfile
Labels: needs/lgtm, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs
