Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2021-07, with the labels that each got.

#320 Add a link to the cherry-pick-pr script from gardener
  Makefile
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#322 Switch leader election to leases
  charts/gardener-extension-provider-alicloud/values.yaml
  cmd/gardener-extension-provider-alicloud/app/app.go
  example/controller-registration.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#323 Improve docs/usage-as-end-user.md
  docs/usage-as-end-user.md
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#329 Set minAllowed memory for csi-disk-plugin containers
  charts/internal/shoot-system-components/charts/csi-alicloud/templates/vpa.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#328 Clean up handling for unsupported K8s versions
  README.md
  charts/gardener-extension-provider-alicloud/templates/_helpers.tpl
  charts/images.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/values.yaml
  charts/internal/shoot-storageclasses/templates/_helpers.tpl
  charts/internal/shoot-system-components/charts/csi-alicloud/values.yaml
  example/10-fake-shoot-controlplane.yaml
  example/30-controlplane.yaml
  example/30-worker.yaml
  example/controller-registration.yaml
  test/e2e/netpol-gen/app/alicloud.go
  test/e2e/networkpolicies/networkpolicy_test.go
Labels: kind/cleanup, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/m
