Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2021-10, with the labels that each got.

#366 [release-v1.27] Automated cherry pick of #365: Add VPA for control plane CSI components
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-plugin-controller-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-controller-vpa.yaml
  cmd/gardener-extension-provider-alicloud/app/app.go
  go.mod
  pkg/controller/controlplane/valuesprovider.go
  vendor/modules.txt
Labels: area/storage, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#367 Move document from g/documentation
  docs/tutorials/kubernetes-cluster-in-alicloud-with-gardener/_index.md
  docs/tutorials/kubernetes-cluster-in-alicloud-with-gardener/images/Alibaba---Create-Custom-Policy.png
  docs/tutorials/kubernetes-cluster-in-alicloud-with-gardener/images/Alibaba---Create-Technical-User.png
  docs/tutorials/kubernetes-cluster-in-alicloud-with-gardener/images/Alibaba---Grant-Permissions.png
  docs/tutorials/kubernetes-cluster-in-alicloud-with-gardener/images/Alibaba-Cloud---copy-required-policies-from-Gardener-dashboard.png
  docs/tutorials/kubernetes-cluster-in-alicloud-with-gardener/images/Copy-icon.png
  docs/tutorials/kubernetes-cluster-in-alicloud-with-gardener/images/Create-new-project-in-Gardener.png
  docs/tutorials/kubernetes-cluster-in-alicloud-with-gardener/images/Gardener---Add-Alibaba-Cloud-Secret.png
  docs/tutorials/kubernetes-cluster-in-alicloud-with-gardener/images/Gardener---Assign-Alibaba-Cloud-Secret.png
  docs/tutorials/kubernetes-cluster-in-alicloud-with-gardener/images/Help-icon.png
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, platform/alicloud

#370 Upgrade csi-plugin-alicloud version
  charts/images.yaml
Labels: area/open-source, kind/enhancement, kind/test, needs/ok-to-test, needs/changes, needs/review, size/xs, platform/alicloud
