Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2021-05, with the labels that each got.

#278 fix nil pointer issue
  pkg/alicloud/client/client.go
Labels: area/robustness, kind/bug, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#280 disable strict mode of decoder
  pkg/controller/controlplane/valuesprovider.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#282 Revert "[ci:component:github.com/gardener/terraformer:v2.5.0->v2.6.0]"
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#285 Update the example Shoot manifest to make strict decoding happy
  docs/usage-as-end-user.md
  example/30-controlplane.yaml
Labels: kind/cleanup, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#286 Do not use strict decoding for ControlPlaneConfig in admission-alicloud
  pkg/admission/validator/shoot.go
Labels: kind/bug, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#289 Fix the ./.ci/prepare_release script
  .ci/prepare_release
  hack/.ci/prepare_release
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/s

#287 Replace infra Helm chart with native Go templates
  charts/internal/alicloud-infra/Chart.yaml
  charts/internal/alicloud-infra/values.yaml
  go.mod
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/actuator_test.go
  pkg/controller/infrastructure/templates/main.tpl.tf
  pkg/controller/infrastructure/templates/terraform.tpl.tfvars
  pkg/controller/infrastructure/templates/variables.tpl.tf
  pkg/controller/infrastructure/terraform.go
  test/integration/infrastructure/infrastructure_test.go
  vendor/github.com/gardener/gardener/pkg/chartrenderer/mock/doc.go
  vendor/github.com/gardener/gardener/pkg/chartrenderer/mock/mocks.go
  vendor/modules.txt
Labels: area/open-source, kind/cleanup, kind/test, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/m

#290 vendor g/g 1.22.3
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/charts/images.yaml
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/metricsserver/metrics_server.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, platform/alicloud, reviewed/lgtm, size/xs

#288 Add validation for cloud provider Secrets
  charts/gardener-extension-admission-alicloud/charts/application/templates/validatingwebhook-validator.yaml
  cmd/gardener-extension-admission-alicloud/app/app.go
  docs/local-setup.md
  example/40-validatingwebhookconfiguration.yaml
  hack/dev-setup-admission-alicloud.sh
  pkg/admission/cmd/options.go
  pkg/admission/validator/secrets.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/webhook.go
  pkg/apis/alicloud/validation/secrets.go
  pkg/apis/alicloud/validation/secrets_test.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/index/index.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/secret/secret.go
  vendor/modules.txt
Labels: area/ops-productivity, area/robustness, kind/enhancement, needs/changes, needs/ok-to-test, needs/review, needs/second-opinion, platform/alicloud, size/l

#294 Revert "Fix the ./.ci/prepare_release script"
  .ci/prepare_release
  hack/.ci/prepare_release
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#284 Clean up the stale target build stage
  Dockerfile
Labels: kind/cleanup, lifecycle/stale, needs/ok-to-test, reviewed/lgtm, size/xs

#295 [release-v1.24] Regenerated controllerregistration
  example/controller-registration.yaml
Labels: area/delivery, kind/cleanup, needs/ok-to-test, needs/review, platform/alicloud, size/xs

#296 Vendor gardener/gardener@v1.23.1
  example/controller-registration.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/charts/images.yaml
  vendor/github.com/gardener/gardener/hack/generate-controller-registration.sh
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#298 Specify the provider field for the MachineClasses
  charts/internal/machineclass/templates/machineclass.yaml
Labels: kind/bug, kind/regression, needs/ok-to-test, reviewed/lgtm, size/xs

#299 [release-v1.24] Automated cherry pick of #298: Specify the provider field for the MachineClasses
  charts/internal/machineclass/templates/machineclass.yaml
Labels: kind/bug, kind/regression, needs/ok-to-test, reviewed/lgtm, size/xs

#302 Update the admission-alicloud RBAC after cloud provider Secrets validation feature
  charts/gardener-extension-admission-alicloud/charts/application/templates/rbac.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
