Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2021-02, with the labels that each got.

#235 vendor g/g 1.16.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, platform/alicloud, priority/normal, size/xs

#234 VPA for validator/admission component
  charts/gardener-extension-validator-alicloud/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-validator-alicloud/values.yaml
Labels: area/auto-scaling, area/scalability, kind/enhancement, needs/ok-to-test, platform/alicloud, priority/normal, reviewed/lgtm, size/s

#239 vendor g/g 1.16.3
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/hack/install-promtool.sh
  vendor/github.com/gardener/gardener/pkg/utils/imagevector/imagevector.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, platform/alicloud, priority/normal, reviewed/lgtm, size/xs

#237 remove shared vpc for integration tests
  .ci/testruns/default/templates/testrun.yaml
  .test-defs/infrastructure-test.yaml
  test/integration/infrastructure/infrastructure_test.go
Labels: area/testing, kind/enhancement, kind/test, needs/ok-to-test, needs/review, platform/alicloud, priority/normal, size/m

#240 Update kubernetes-csi/external-snapshotter to v2.1.4
  charts/images.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#242 Fix machine-controller-manager-provider-alicloud image tag
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
