Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2022-06, with the labels that each got.

#494 Vendor gardener/machine-controller-manager@v0.45.0
  go.mod
  go.sum
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/alicoud_machineclass_types.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#496 fix tm integration testing
  pkg/controller/infrastructure/actuator.go
Labels: kind/test, needs/ok-to-test, reviewed/lgtm, size/xs, platform/alicloud, area/testing

#505 Fix usage of deprecated fields in the terraform configuration file
  pkg/controller/infrastructure/templates/main.tpl.tf
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, platform/alicloud

#504 Change base image from alpine to distroless
  Dockerfile
Labels: area/open-source, area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/alicloud

#503 Add parsers for csi-snapshot pods
  charts/gardener-extension-provider-alicloud/templates/configmap-logging.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-controller-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-controller.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-validation-webhook-deployment.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-validation-webhook-vpa.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/alicloud
