Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2023-06, with the labels that each got.

#609 Support for Kubernetes v1.27
  README.md
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, topology/garden, topology/seed, topology/shoot, platform/alicloud, merge/squash

#612 Update external-provisioner to version 3.2.2
  charts/images.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/alicloud

#614 Set responsibles for Alicloud
  .ci/pipeline_definitions
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#618 Allow access to webhook server from shoot API servers
  charts/gardener-extension-provider-alicloud/templates/service.yaml
  example/controller-registration.yaml
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#622 [release-v1.46] Automated cherry pick of #607: [ci:component:github.com/gardener/machine-controller-manager:v0.49.0->v0.49.2] #621: [ci:component:github.com/gardener/machine-controller-manager:v0.49.2->v0.49.3]
  charts/images.yaml
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#620 Fix namespace selector
  charts/gardener-extension-provider-alicloud/templates/service.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#613 upgrade csi
  charts/images.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-validation-webhook-deployment.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml
  charts/internal/shoot-storageclasses/templates/_helpers.tpl
  charts/internal/shoot-storageclasses/templates/storageclasses.yaml
  charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-snapshot-controller-rbac.yaml
  charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-snapshot-validation-rbac.yaml
  charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-snapshotter-rbac.yaml
  pkg/alicloud/types.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/healthcheck/add.go
  pkg/webhook/controlplane/ensurer.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/rebase, needs/second-opinion, size/xl, platform/alicloud

#608 Upgrade Aliyun CSI plugin
  charts/images.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#616 Switch remaining images from `k8s.gcr.io` to `registry.k8s.io`
  charts/images.yaml
Labels: area/quality, kind/bug, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#617 Adapt to new `MachineControllerManagerDeployment` feature gate
  charts/gardener-extension-provider-alicloud/templates/deployment.yaml
  charts/gardener-extension-provider-alicloud/values.yaml
  cmd/gardener-extension-provider-alicloud/app/app.go
  example/controller-registration.yaml
  pkg/controller/healthcheck/add.go
  pkg/controller/worker/actuator.go
  pkg/controller/worker/add.go
  pkg/webhook/controlplane/add.go
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
  vendor/github.com/gardener/gardener/pkg/utils/test/gomock.go
  vendor/github.com/gardener/gardener/pkg/utils/test/manager.go
  vendor/github.com/gardener/gardener/pkg/utils/test/options.go
  vendor/github.com/gardener/gardener/pkg/utils/test/test.go
  vendor/github.com/gardener/gardener/pkg/utils/test/test_resources.go
  vendor/modules.txt
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, size/l

#624 correct labels of csi-alicloud
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-validation-webhook-deployment.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#619 Drop code related to `APIServerSNI` feature gate
  charts/gardener-extension-provider-alicloud/templates/configmap.yaml
  charts/gardener-extension-provider-alicloud/values.yaml
  cmd/gardener-extension-provider-alicloud/app/app.go
  example/00-componentconfig.yaml
  example/controller-registration.yaml
  hack/api-reference/config.md
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/webhook/controlplaneexposure/add.go
  pkg/webhook/controlplaneexposure/ensurer.go
  pkg/webhook/controlplaneexposure/ensurer_test.go
Labels: area/dev-productivity, kind/api-change, kind/cleanup, needs/ok-to-test, needs/rebase, needs/review, needs/second-opinion, reviewed/ok-to-test, size/l

#626 revert alicloud-csi-plugin
  charts/images.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, needs/review, reviewed/ok-to-test, size/xs, platform/alicloud
