Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2023-12, with the labels that each got.

#668 Update testmachinery image location
  .ci/pipeline_definitions
Labels: area/delivery, kind/task, needs/ok-to-test, needs/review, reviewed/lgtm, size/xs, platform/alicloud

#669 Prepare switch to artifact registry
  .ci/pipeline_definitions
Labels: area/delivery, kind/technical-debt, kind/cleanup, needs/ok-to-test, needs/rebase, needs/review, size/xs, platform/alicloud

#667 Optimize CCM network flag by seed provider
  charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/values.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#670 Change metric port
  charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/alicloud-ccm-service.yaml
  charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/deployment.yaml
Labels: area/monitoring, kind/bug, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#672 Change metric port
  charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/alicloud-ccm-service.yaml
  charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/deployment.yaml
Labels: area/monitoring, kind/bug, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#673 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  Makefile
  charts/gardener-extension-admission-alicloud/values.yaml
  charts/gardener-extension-provider-alicloud/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/s

#675 fix typos
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#676 Add Kubernetes v1.28 conformance test badge
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#666 Replaced absolute link with relative
  docs/operations/operations.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, reviewed/ok-to-test, size/xs, platform/alicloud
