Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2023-01, with the labels that each got.

#559 Add cve categorizations/runtime contexts
  charts/images.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, needs/review, size/s, platform/alicloud

#551 disable network overlay for cilium by default and extend tests
  go.mod
  go.sum
  pkg/admission/mutator/shoot.go
  pkg/admission/mutator/shoot_test.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/LICENSE.md
  vendor/github.com/gardener/gardener-extension-networking-cilium/NOTICE.md
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/doc.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/register.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/doc.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/register.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/cilium/predicates.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/cilium/types.go
  vendor/modules.txt
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/m, platform/alicloud

#562 Add CVE runtime context for `MCM` and `mcm-provider-alicloud`
  charts/images.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/alicloud

#561 Add Fluent Operator resources
  charts/gardener-extension-provider-alicloud/templates/clusterfilters-logging.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, needs/review, size/s, platform/alicloud

#560 Support for Kubernetes v1.26
  README.md
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, needs/review, size/xs, topology/garden, topology/seed, topology/shoot, platform/alicloud, merge/squash
