Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2023-10, with the labels that each got.

#650 Support for Kubernetes v1.28
  README.md
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, needs/review, size/xs, topology/garden, topology/seed, topology/shoot, platform/alicloud, merge/squash

#648 Change volumeBindingMode to WaitForFirstConsumer
  charts/internal/shoot-storageclasses/templates/storageclasses.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/alicloud

#651 allow public network access
  charts/gardener-extension-admission-alicloud/charts/runtime/templates/deployment.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#641 Introduce the use of central manifest
  .ci/verify
  .docforge/manifest.yaml
  Makefile
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, platform/alicloud

#657 fix: Concourse build badge URL
  README.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, needs/review, size/xs, platform/alicloud
