Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2024-12, with the labels that each got.

#745 update CCM to 2.10.0
  imagevector/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#744 Update Kubernetes 1.31 conformance test coverage
  README.md
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#740 export egress cidrs to status
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/actuator_flow.go
  pkg/controller/infrastructure/actuator_test.go
  pkg/controller/infrastructure/tf_migration.go
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, needs/review, size/s, platform/alicloud

#749 Remove the provider type predicates in webhooks
  pkg/admission/mutator/webhook.go
  pkg/admission/validator/webhook.go
Labels: area/usability, kind/cleanup, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#747 Fixes Alicloud bastion instance CPU architecture not aligning with the image CPU architecture in certain conditions
  pkg/alicloud/client/client.go
  pkg/alicloud/client/types.go
  pkg/controller/bastion/actuator_reconcile.go
  pkg/mock/provider-alicloud/alicloud/client/mocks.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, needs/review, size/m, platform/alicloud
