Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2024-04, with the labels that each got.

#705 Update bastion-test imageId
  test/integration/bastion/bastion_test.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud, area/testing

#703 add operatingsystem label
  charts/internal/machineclass/templates/machineclass.yaml
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, needs/rebase, needs/review, size/xs, platform/alicloud

#706 drop mcm
  charts/gardener-extension-provider-alicloud/templates/clusterfilters-logging.yaml
  charts/internal/machine-controller-manager/seed/Chart.yaml
  charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  charts/internal/machine-controller-manager/seed/templates/clusterrolebinding.yaml
  charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/poddisruptionbudget.yaml
  charts/internal/machine-controller-manager/seed/templates/service.yaml
  charts/internal/machine-controller-manager/seed/templates/serviceaccount.yaml
  charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/machine-controller-manager/shoot/Chart.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
  pkg/alicloud/types.go
  pkg/controller/worker/add.go
  pkg/controller/worker/machine_controller_manager.go
Labels: area/control-plane, area/open-source, kind/cleanup, needs/ok-to-test, needs/second-opinion, size/xl, platform/alicloud

#709 Csi plugin update
  charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-plugin-rbac.yaml
  charts/internal/shoot-system-components/charts/csi-alicloud/templates/csi-diskplugin-ds.yaml
  charts/internal/shoot-system-components/charts/csi-alicloud/values.yaml
  imagevector/images.yaml
  pkg/alicloud/types.go
  pkg/controller/controlplane/valuesprovider.go
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#714 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, kind/cleanup, needs/ok-to-test, needs/review, size/s

#713 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, kind/cleanup, needs/ok-to-test, needs/review, size/s

#712 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, kind/cleanup, needs/ok-to-test, needs/review, size/s

#711 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, kind/cleanup, needs/ok-to-test, needs/review, size/s

#710 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, kind/cleanup, needs/ok-to-test, needs/review, size/s
