Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2024-02, with the labels that each got.

#689 update csi-plugin-alicloud version
  imagevector/images.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#692 revert csi-plugin-alicloud
  imagevector/images.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#693 Add Kubernetes v1.29 conformance test badge
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#690 Adapt PDBs to use `unhealthyPodEvictionPolicy: AlwaysAllow`
  charts/gardener-extension-admission-alicloud/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-admission-alicloud/charts/runtime/templates/service.yaml
  charts/gardener-extension-provider-alicloud/templates/poddisruptionbudget.yaml
  charts/gardener-extension-provider-alicloud/templates/service.yaml
  charts/internal/machine-controller-manager/seed/templates/poddisruptionbudget.yaml
  charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/poddisruptionbudget.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-plugin-controller-poddisruptionbudget.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-controller-poddisruptionbudget.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-validation-webhook-poddisruptionbudget.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-validation-webhook-service.yaml
  example/controller-registration.yaml
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud
