Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2025-09, with the labels that each got.

#821 Bump github.com/gardener/gardener from v1.122.1 to v1.123.1
  example/20-crd-extensions.gardener.cloud_controlplanes.yaml
  go.mod
  go.sum
  pkg/controller/controlplane/add.go
  test/integration/healthcheck/test.go
Labels: area/control-plane, kind/enhancement, needs/review, reviewed/ok-to-test, size/m, platform/alicloud

#823 Update the regex selector for the unused MCM RBAC resources
  cmd/gardener-extension-provider-alicloud/app/migrations.go
Labels: kind/bug, kind/cleanup, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/alicloud, area/compliance

#827 export testresults as inlined ocm-resource
  .github/workflows/build.yaml
Labels: kind/task, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/alicloud, area/compliance

#828 Update the build badge from Concourse to GitHub Actions
  README.md
Labels: area/delivery, kind/cleanup, needs/review, reviewed/ok-to-test, size/xs, platform/alicloud

#834 Adjust required permissions for `upgrade-dependencies.yaml` workflow
  .github/workflows/upgrade-dependencies.yaml
Labels: needs/review, reviewed/ok-to-test, size/xs, platform/alicloud

#833 Add generation for `Extension` example
  Makefile
  example/controller-registration.yaml
  example/doc.go
  example/extension.yaml
  example/extension/base/extension.yaml
  example/extension/base/kustomization.yaml
  example/extension/kustomization.yaml
Labels: area/ops-productivity, kind/enhancement, needs/review, reviewed/ok-to-test, size/m, platform/alicloud

#835 1.64 fix flow zone worker
  pkg/apis/alicloud/validation/infrastructure.go
  pkg/apis/alicloud/validation/infrastructure_test.go
  pkg/controller/infrastructure/infraflow/reconcile_zone.go
Labels: area/control-plane, kind/enhancement, needs/review, reviewed/ok-to-test, size/s, platform/alicloud

#838 Add conformance test badge for Kubernetes v1.33
  README.md
Labels: reviewed/ok-to-test
