Repository gardener/gardener-extension-provider-alicloud, pull requests merged in 2025-07, with the labels that each got.

#805 refactor flow base
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/actuator_delete.go
  pkg/controller/infrastructure/actuator_flow.go
  pkg/controller/infrastructure/actuator_migrate.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/controller/infrastructure/actuator_restore.go
  pkg/controller/infrastructure/flow_reconciler.go
  pkg/controller/infrastructure/infraflow/reconcile_zone.go
  pkg/controller/infrastructure/shoot_encrypted_image.go
  pkg/controller/infrastructure/strategyselector.go
  pkg/controller/infrastructure/tf_reconciler.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, size/xl, platform/alicloud

#807 update ali csi plugin
  imagevector/images.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#808 update ali csi plugin
  imagevector/images.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#809 update ali csi plugin
  imagevector/images.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#812 update ali csi plugin to v1.31.4-75f6f4a-aliyun
  imagevector/images.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#811 update ali csi plugin to v1.31.4-75f6f4a-aliyun
  imagevector/images.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#813 update ali csi plugin to v1.31.4-75f6f4a-aliyun
  imagevector/images.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/alicloud

#817 Bump github.com/gardener/gardener from v1.121.1 to v1.122.1
  .ci/hack/component_descriptor
  .ci/hack/doc.go
  .ci/hack/prepare_release
  .ci/hack/set_dependency_version
  example/20-crd-extensions.gardener.cloud_backupbuckets.yaml
  example/20-crd-extensions.gardener.cloud_backupentries.yaml
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  example/20-crd-extensions.gardener.cloud_clusters.yaml
  example/20-crd-extensions.gardener.cloud_containerruntimes.yaml
  example/20-crd-extensions.gardener.cloud_controlplanes.yaml
  example/20-crd-extensions.gardener.cloud_dnsrecords.yaml
  example/20-crd-extensions.gardener.cloud_extensions.yaml
  example/20-crd-extensions.gardener.cloud_infrastructures.yaml
  example/20-crd-extensions.gardener.cloud_networks.yaml
  example/20-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  example/20-crd-extensions.gardener.cloud_workers.yaml
  example/20-crd-resources.gardener.cloud_managedresources.yaml
  go.mod
  go.sum
  pkg/admission/validator/namespacedcloudprofile.go
  pkg/controller/healthcheck/add.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, size/l, platform/alicloud

#815 Updating cnudie labels
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/s, platform/alicloud

#816 Update csi image version
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-validation-webhook-deployment.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-validation-webhook-poddisruptionbudget.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-validation-webhook-service.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-snapshot-validation-webhook-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-alicloud/values.yaml
  charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-snapshot-validation-rbac.yaml
  charts/internal/shoot-system-components/charts/csi-alicloud/templates/csi-snaphot-validation-webhook.yaml
  charts/internal/shoot-system-components/charts/csi-alicloud/values.yaml
  imagevector/images.yaml
  pkg/alicloud/types.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/healthcheck/add.go
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, reviewed/ok-to-test, size/l, platform/alicloud

#818 Drop support for Shoots with Kubernetes version <= 1.28
  README.md
  docs/usage/usage.md
  example/10-fake-shoot-controlplane.yaml
  example/30-controlplane.yaml
  example/30-worker.yaml
  pkg/apis/alicloud/validation/controlplane_test.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s, platform/alicloud

#824 Run integrationtests
  .github/workflows/release.yaml
  .github/workflows/upgrade-dependencies.yaml
Labels: area/delivery, kind/task, needs/review, reviewed/ok-to-test, size/xs, platform/alicloud
